[project]
name = "file-upload"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docx2txt>=0.8",
    "pdfplumber>=0.11.5",
    "streamlit>=1.42.0",
]
